networks:
  weewarnetwork:
    external: true

services:
#    pgadmin:
#    networks:
#      - weewarnetwork
#      image: dpage/pgadmin4
#      ports:
#        - ${PGADMIN_LISTEN_PORT}:${PGADMIN_LISTEN_PORT}
#      environment:
#        PGADMIN_LISTEN_PORT: ${PGADMIN_LISTEN_PORT}
#        PGADMIN_DEFAULT_EMAIL: ${PGADMIN_DEFAULT_EMAIL}
#        PGADMIN_DEFAULT_PASSWORD: ${PGADMIN_DEFAULT_PASSWORD}
#      volumes:
#        - ./.data/pgadmin:/var/lib/pgadmin

  postgres:
    networks:
      - weewarnetwork
    image: arm64v8/postgres:16.3
      # image: postgres:15.3
    environment:
      POSTGRES_DB: ${POSTGRES_DB}
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
    volumes:
      - ./.data/pgdata:/var/lib/postgresql/data
        # - ./configs/postgresql.conf:/var/lib/postgresql/data/postgresql.conf:ro
    ports:
      - 54321:5432
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres"]
      interval: 5s
      timeout: 5s
      retries: 5
