networks:
  lilbattlenetwork:
    external: true

services:
  lilbattle:
    networks:
      - lilbattlenetwork
    build:
      context: .
      dockerfile: ./cmd/backend/Dockerfile
    volumes:
      # - ./.air.toml:/app/.air.toml:ro
      # - ./go.mod:/app/go.mod:ro
      # - ./go.sum:/app/go.sum:ro
      - ./cmd:/app/cmd
      - ./web:/app/web
      - ./protos:/app/protos
      - ./services:/app/services
      - ./utils:/app/utils
      - ./gen:/app/gen
      - ./.env:/app/.env
      - ./.env.dev:/app/.env.dev
        # command: ["air", "-c", "cmd/backend/.air.toml"]
    environment:
      POSTGRES_HOST: ${POSTGRES_HOST}
      POSTGRES_PORT: ${POSTGRES_PORT}
      POSTGRES_DB: ${POSTGRES_DB}
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      LILBATTLE_DB_ENDPOINT: ${LILBATTLE_DB_ENDPOINT}
      OTEL_RESOURCE_ATTRIBUTES: service.name=onehub.backend,service.version=0.0.1
      LILBATTLE_ENV: dev 
    ports:
      - 6060:6060
      - 7070:7070
      - 8080:8080
      - 9090:9090
